services:
  - type: web
    name: epa-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_EMAIL_DOMAIN
        value: ujap.edu.ve

  - type: web
    name: epa-web
    runtime: static
    buildCommand: npm install && npx expo export -p web
    staticPublishPath: ./dist
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://epa-ujap.onrender.com
